### PR TITLE
Issue #21

### PR DESCRIPTION
**Pull request by serpest**
Home title centered.

I didn't change the circle tracker font size because the UI is very simple, so a big font is better in my opinion.

### CODE REVIEW

**Comment by serpest** [comment]
I solved the problem.
I also changed the tracker position and text. Now I think it's useful.
I moved the total clicks number in a variable, so you can implement a setting to change it before pressing the start button.

**Comment by serpest** [comment]
I committed a new fix.
However the VBox used in the home screen has a problem: its alignment doesn't consider its size. Can you help me?

**Comment by serpest** [comment]
Done!

**Comment by AndrreyCastillo** [comment]
Looks good! Thanks a lot!

**Pull request merged**
